Repository TheCherno/Hazel, pull requests merged in 2019-08, with the labels that each got.

#92 Fix warning casting from 'const uint32_t' to 'const void*'
  Hazel/src/Platform/OpenGL/OpenGLVertexArray.cpp
Labels: Warning

#93 Fixed a bug in LayerStack which would occur if passing an overlay or …
  Hazel/src/Hazel/LayerStack.cpp
Labels: Bug

#102 Fix for bug in Vertex Array
  Hazel/src/Platform/OpenGL/OpenGLVertexArray.cpp
  Hazel/src/Platform/OpenGL/OpenGLVertexArray.h
Labels: Impact:Bug

#105 Fix a warning introduced by PR
  Hazel/src/Platform/OpenGL/OpenGLVertexArray.cpp
  Hazel/src/Platform/OpenGL/OpenGLVertexArray.h
Labels: Impact:Optimization, Impact:Warning

#83 Smoother project generation
  GenerateProjects.bat
Labels: Impact:Suggestion

#98 Adding flag for MultiProcessor Compilation in Premake
  premake5.lua
Labels: Impact:Optimization, Support:Premake

#107 Change bind target inside OpenGLIndexBuffer constructor
  Hazel/src/Platform/OpenGL/OpenGLBuffer.cpp
Labels: Impact:Bug

#111 Made Input a Singleton
  Hazel/src/Hazel/Input.h
Labels: Impact:Optimization

#106 Avoid using std::function for performance
  Hazel/src/Hazel/Events/Event.h
Labels: Impact:Optimization
