Repository TheCherno/Hazel, pull requests merged in 2019-12, with the labels that each got.

#180 Additions to the Coding Conventions and Pull Request sections in the Contribution Guidelines
  .github/CONTRIBUTING.md
Labels: Support:git

#174 created __FUNCSIG__ definition for unix compilers
  Hazel/src/Hazel/Debug/Instrumentor.h
Labels: Impact:Bug

#114 Implementation of OpenGL messages
  Hazel/src/Hazel/Core/Log.cpp
  Hazel/src/Platform/OpenGL/OpenGLRendererAPI.cpp
  Hazel/src/Platform/Windows/WindowsWindow.cpp
Labels: Impact:Feature, Support:Debug

#124 Replaced the KeyCodes and MouseButtonCodes defines with enum classes
  Hazel/src/Hazel.h
  Hazel/src/Hazel/Core/Input.h
  Hazel/src/Hazel/Core/KeyCodes.h
  Hazel/src/Hazel/Core/MouseButtonCodes.h
  Hazel/src/Hazel/Core/MouseCodes.h
  Hazel/src/Hazel/Events/KeyEvent.h
  Hazel/src/Hazel/Events/MouseEvent.h
  Hazel/src/Platform/Windows/WindowsInput.cpp
  Hazel/src/Platform/Windows/WindowsInput.h
  Hazel/src/Platform/Windows/WindowsWindow.cpp
  Sandbox/src/SandboxApp.cpp
Labels: Impact:Feature
