Repository TheCherno/Hazel, pull requests merged in 2019-10, with the labels that each got.

#122 Adding VS files to gitignore
  .gitignore
  Hazel/vendor/Glad/Glad.vcxproj
  Hazel/vendor/Glad/Glad.vcxproj.filters
Labels: Impact:Suggestion, Support:git

#80 Templates for Issues & Pull requests (issue #29)
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/issue--blank-template.md
  .github/ISSUE_TEMPLATE/issue--bug-report.md
  .github/ISSUE_TEMPLATE/issue--feature-request.md
  .github/PULL_REQUEST_TEMPLATE/pull-request--implemented-issue.md
  .github/PULL_REQUEST_TEMPLATE/pull-request--new-issue.md
Labels: Impact:Suggestion, Support:git

#145 Added the required YAML front matter to templates
  .github/ISSUE_TEMPLATE/issue--blank-template.md
  .github/ISSUE_TEMPLATE/issue--bug-report.md
  .github/ISSUE_TEMPLATE/issue--feature-request.md
  .github/PULL_REQUEST_TEMPLATE/pull-request--implemented-issue.md
  .github/PULL_REQUEST_TEMPLATE/pull-request--new-issue.md
Labels: Impact:Bug, Support:git

#113 Remove unnecessary token-pasting operator in EVENT_CLASS_TYPE
  Hazel/src/Hazel/Events/Event.h
Labels: Impact:Warning

#127 Delete the shaders after the shader program Creation
  Hazel/src/Platform/OpenGL/OpenGLShader.cpp
Labels: Impact:Bug

#146 Call the layer's OnDetach before deleting it. (#126)
  Hazel/src/Hazel/Core/LayerStack.cpp
Labels: Impact:Duplicate

#132 Automated platform detection using predefined macro's
  Hazel/src/Hazel/Core/Core.h
  premake5.lua
Labels: Impact:Optimization, Support:Premake

#135 Fixed OpenGLShader::PreProcess Logic (issue #120)
  Hazel/src/Platform/OpenGL/OpenGLShader.cpp
Labels: Impact:Suggestion

#137 Added check for OpenGL 4.5
  Hazel/src/Platform/OpenGL/OpenGLContext.cpp
Labels: Impact:Suggestion

#138 Fixes for OrthographicCameraController Movement
  Hazel/src/Hazel/Renderer/OrthographicCameraController.cpp
  Hazel/src/Hazel/Renderer/OrthographicCameraController.h
Labels: Impact:Bug

#129 Use 'Scope's instead of raw pointers
  Hazel/src/Hazel/Core/Core.h
  Hazel/src/Hazel/Core/Input.h
  Hazel/src/Hazel/Renderer/RenderCommand.cpp
  Hazel/src/Hazel/Renderer/RenderCommand.h
  Hazel/src/Hazel/Renderer/Renderer.cpp
  Hazel/src/Hazel/Renderer/Renderer.h
  Hazel/src/Hazel/Renderer/Shader.cpp
  Hazel/src/Platform/Windows/WindowsInput.cpp
  Hazel/src/Platform/Windows/WindowsWindow.cpp
  Hazel/src/Platform/Windows/WindowsWindow.h
Labels: Impact:Bug

#128 Implemented a basic ref-counting system to terminate glfw
  Hazel/src/Platform/Windows/WindowsWindow.cpp
Labels: Impact:Bug, Impact:Feature

#157 PR template(s) not showing
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/pull-request--new-issue.md
Labels: Impact:Bug, Support:git

#144 Fix Build warnings to do with BufferElement Offset Type
  Hazel/src/Hazel/Renderer/Buffer.h
  Hazel/src/Platform/OpenGL/OpenGLVertexArray.cpp
Labels: Impact:Warning

#156 Made Win-GenProjects.bat work from every directory
  scripts/Win-GenProjects.bat
Labels: Impact:Bug, OS:Windows, Support:Premake
