Repository TheCherno/Hazel, pull requests merged in 2019-11, with the labels that each got.

#168 Added file reading sanity check
  Hazel/src/Platform/OpenGL/OpenGLShader.cpp
Labels: Impact:Warning

#170 Move 3D Layer to Separate Files
  Sandbox/src/ExampleLayer.cpp
  Sandbox/src/ExampleLayer.h
  Sandbox/src/SandboxApp.cpp
Labels: Impact:Suggestion

#169 Missing Iterator Wrappers in LayerStack.h
  Hazel/src/Hazel/Core/Application.cpp
  Hazel/src/Hazel/Core/LayerStack.h
Labels: Impact:Bug, Impact:Suggestion

#172 Premake architecture parameter fix
  premake5.lua
Labels: Impact:Bug
