Repository TheCherno/Hazel, pull requests merged in 2020-12, with the labels that each got.

#374 Make Open and Save file dialogs start from current working directory
  Hazel/src/Platform/Windows/WindowsPlatformUtils.cpp
Labels: Impact:Suggestion

#376 Changed std::unique_ptr to Scope in Application.h
  Hazel/src/Hazel/Core/Application.h
Labels: Impact:Maintenance

#362 Fixed Z-Fighting bug in Texture Shader and updated GLSL version
  Hazelnut/assets/shaders/Texture.glsl
  Sandbox/assets/shaders/Texture.glsl
Labels: Impact:Bug

#388 Fixed Math Function Declaration
  Hazel/src/Hazel/Math/Math.h
Labels: Impact:Bug

#389 Removed redundant include in WindowsPlatformUtils.cpp file
  Hazel/src/Platform/Windows/WindowsPlatformUtils.cpp
Labels: Impact:Maintenance
