Repository TheCherno/Hazel, pull requests merged in 2020-01, with the labels that each got.

#179 Instrumentation fixes for #176 and #181
  Hazel/src/Hazel/Debug/Instrumentor.h
  Sandbox/HazelProfile-Runtime.json
  Sandbox/HazelProfile-Shutdown.json
  Sandbox/HazelProfile-Startup.json
Labels: Impact:Bug

#190 compile time check of window type and input type
  Hazel/src/Hazel/Core/Input.cpp
  Hazel/src/Hazel/Core/Input.h
  Hazel/src/Hazel/Core/Window.cpp
  Hazel/src/Platform/Windows/WindowsInput.cpp
  Hazel/src/Platform/Windows/WindowsWindow.cpp
Labels: Impact:Optimization

#188 make main runloop only accessible on the engine side
  Hazel/src/Hazel/Core/Application.h
Labels: Impact:Suggestion

#185 Fixed Instrumentor generating same start time
  Hazel/src/Hazel/Debug/Instrumentor.h
Labels: Impact:Maintenace, Impact:Suggestion
