Repository TheCherno/Hazel, pull requests merged in 2020-05, with the labels that each got.

#230 delete QuadVertexBufferBase on shutdown
  Hazel/src/Hazel/Renderer/Renderer2D.cpp
Labels: Impact:Bug

#234 Fix tint color not being used in Renderer2D
  Hazel/src/Hazel/Renderer/Renderer2D.cpp
Labels: Impact:Bug

#219 Imgui Swallowing
  Hazel/src/Hazel/Core/Application.cpp
  Hazel/src/Hazel/ImGui/ImGuiLayer.cpp
  Hazel/src/Hazel/ImGui/ImGuiLayer.h
Labels: Impact:Feature

#240 fixed the '__cdecl' output in Instrumentor.h in a 'constexpr' way
  Hazel/src/Hazel/Debug/Instrumentor.h
Labels: Impact:Optimization

#226 Fixed default value for indexCount in OpenGLRendererAPI::DrawIndexed
  Hazel/src/Hazel/Renderer/Renderer.cpp
  Hazel/src/Hazel/Renderer/Renderer2D.cpp
  Hazel/src/Hazel/Renderer/RendererAPI.h
Labels: Impact:Bug

#247 Branching instead of indexing the texture sampler
  Sandbox/assets/shaders/Texture.glsl
Labels: Impact:Bug

#246 Rename Hazel/Core/Core.h to Hazel/Core/Base.h per episode 49. This is…
  Hazel/src/Hazel.h
  Hazel/src/Hazel/Core/Application.h
  Hazel/src/Hazel/Core/Base.h
  Hazel/src/Hazel/Core/EntryPoint.h
  Hazel/src/Hazel/Core/Input.h
  Hazel/src/Hazel/Core/Layer.h
  Hazel/src/Hazel/Core/LayerStack.h
  Hazel/src/Hazel/Core/Log.h
  Hazel/src/Hazel/Core/Window.h
  Hazel/src/Hazel/Events/Event.h
  Hazel/src/Hazel/Renderer/Texture.h
Labels: Impact:Maintenance
