Repository TheCherno/Hazel, pull requests merged in 2020-04, with the labels that each got.

#207 Fix minor issues in OpenGL buffer creation
  Hazel/src/Platform/OpenGL/OpenGLBuffer.cpp
Labels: Impact:Maintenace

#159 Remove all redundant 'inline' keyword usage.
  Hazel/src/Hazel/Core/Application.h
  Hazel/src/Hazel/Core/Input.h
  Hazel/src/Hazel/Core/Layer.h
  Hazel/src/Hazel/Core/Log.h
  Hazel/src/Hazel/Events/ApplicationEvent.h
  Hazel/src/Hazel/Events/Event.h
  Hazel/src/Hazel/Events/KeyEvent.h
  Hazel/src/Hazel/Events/MouseEvent.h
  Hazel/src/Hazel/Renderer/Buffer.h
  Hazel/src/Hazel/Renderer/RenderCommand.h
  Hazel/src/Hazel/Renderer/Renderer.h
  Hazel/src/Hazel/Renderer/RendererAPI.h
  Hazel/src/Platform/Windows/WindowsWindow.h
Labels: Impact:Optimization, Impact:Suggestion

#213 ImGui set to control square color
  Sandbox/src/Sandbox2D.cpp
Labels: Impact:Bug

#212 General Cleanup
  Hazel/src/Hazel/Core/Application.cpp
  Hazel/src/Hazel/Core/Core.h
  Hazel/src/Platform/OpenGL/OpenGLContext.cpp
  premake5.lua
Labels: Impact:Maintenance

#217 Index count selection fixed in OpenGLRendererAPI
  Hazel/src/Platform/OpenGL/OpenGLRendererAPI.cpp
Labels: Impact:Bug

#210 Renderer2D: Replace vertex setup code with a for loop.
  Hazel/src/Hazel/Renderer/Renderer2D.cpp
Labels: Impact:Maintenance

#218 Added flush when textures exceed max texture slots
  Hazel/src/Hazel/Renderer/Renderer2D.cpp
Labels: Impact:Bug

#223 Fixed Incorrect Cases in GetComponentCount
  Hazel/src/Hazel/Renderer/Buffer.h
  Hazel/src/Platform/OpenGL/OpenGLVertexArray.cpp
Labels: Impact:Bug

#224 Fixed warning
  Hazel/src/Hazel/Renderer/Renderer2D.cpp
Labels: Impact:Maintenance
