Repository TheCherno/Hazel, pull requests merged in 2020-11, with the labels that each got.

#355 Added a default extension string
  Hazel/src/Platform/Windows/WindowsPlatformUtils.cpp
Labels: Impact:Bug

#363 Change to FileDialogs' methods so that they return std::optional.
  Hazel/src/Hazel/Utils/PlatformUtils.h
  Hazel/src/Platform/Windows/WindowsPlatformUtils.cpp
  Hazelnut/src/EditorLayer.cpp
Labels: Impact:Maintenance

#358 Set vec4 and vec2's encoding style to Flow + use yaml-cpp to load files
  Hazel/src/Hazel/Scene/SceneSerializer.cpp
Labels: Impact:Suggestion

#346 Amended code to conform with C++ standard
  Hazelnut/src/Panels/SceneHierarchyPanel.cpp
Labels: Impact:Maintenance, hacktoberfest-accepted

#359 Warn if user tries to add a component if already present
  Hazelnut/src/Panels/SceneHierarchyPanel.cpp
Labels: Impact:Bug
