Repository TheCherno/Hazel, pull requests merged in 2020-07, with the labels that each got.

#268 Fix black flicker on resize
  Hazelnut/src/EditorLayer.cpp
Labels: Impact:Bug

#281 Renderer2D consolidate DrawRotatedQaud functions
  Hazel/src/Hazel/Renderer/Renderer2D.cpp
  premake5.lua
Labels: Impact:Maintenance

#280 Fixed __LINE__ not expanding in instrumentor
  Hazel/src/Hazel/Debug/Instrumentor.h
Labels: Impact:Bug

#283 Fixed potential memory leak and malformed JSON in Instrumentor.
  Hazel/src/Hazel/Debug/Instrumentor.h
Labels: Impact:Maintenance

#277 replaced std::bind with lambda in HZ_BIND_EVENT_FN macro
  Hazel/src/Hazel/Core/Base.h
Labels: Impact:Optimization

#285 Fix conversion error
  Hazel/src/Hazel/Scene/Entity.h
Labels: Impact:Bug
