Repository TheCherno/Hazel, pull requests merged in 2020-10, with the labels that each got.

#333 Fix Variable Names in Camera GUI and Consistent Function Ordering
  Hazel/src/Hazel/Scene/SceneCamera.cpp
  Hazel/src/Hazel/Scene/SceneCamera.h
  Hazelnut/src/Panels/SceneHierarchyPanel.cpp
Labels: Impact:Maintenance

#328 Add EventCategoryMouseButton to MouseButtonEvent
  Hazel/src/Hazel/Events/MouseEvent.h
Labels: Impact:Bug

#290 Updated Readme
  Hazelnut/imgui.ini
  README.md
Labels: Impact:Suggestion, Support:git

#341 Removed warnings from External Dependencies
  Hazel/src/Hazel/Core/Log.h
Labels: Impact:Warning

#321 Removed redundant GetProjection()
  Hazel/src/Hazel/Scene/Scene.cpp
Labels: Impact:Optimization

#324 Fixed two includes to fit the convention and one typo
  Hazel/src/Hazel/Renderer/Framebuffer.cpp
  Hazel/src/Platform/OpenGL/OpenGLFramebuffer.cpp
  Hazel/src/Platform/OpenGL/OpenGLTexture.cpp
Labels: Impact:Maintenance

#306 Allow assert macro to take no arguments
  Hazel/src/Hazel.h
  Hazel/src/Hazel/Core/Assert.h
  Hazel/src/Hazel/Core/Base.h
  Hazelnut/src/Panels/SceneHierarchyPanel.h
Labels: Impact:Maintenance

#347 Removed and replaced code with equivalent standard library function
  Hazel/src/Hazel/Core/Assert.h
Labels: Impact:Maintenance, hacktoberfest-accepted

#344 Add Renderer2D::StartBatch() and make FlushAndReset() not call EndScene()
  Hazel/src/Hazel/Renderer/Renderer2D.cpp
  Hazel/src/Hazel/Renderer/Renderer2D.h
Labels: Impact:Maintenance, hacktoberfest-accepted

#348 Fix imgui crash in Hazelnut
  Hazelnut/imgui.ini
Labels: Impact:Bug, hacktoberfest-accepted

#343 Fix EventDispatcher::Dispatch() resetting Event::Handled to false
  Hazel/src/Hazel/Events/Event.h
Labels: Impact:Bug, hacktoberfest-accepted

#322 passing initializer_list by value, it is cheap to copy it, added const qualifiers, VertexArray now using default virtual destructor
  Hazel/src/Hazel/Renderer/Buffer.h
  Hazel/src/Hazel/Renderer/Renderer2D.h
  Hazel/src/Hazel/Renderer/VertexArray.h
Labels: Impact:Optimization
