Repository TheCherno/Hazel, pull requests merged in 2021-09, with the labels that each got.

#462 Fix typo in README
  README.md
Labels: Support:git, Impact:Maintenance

#455 Set staticruntime to off in Glad project
  Hazel/vendor/Glad/premake5.lua
Labels: Support:Premake, Impact:Bug

#361 Added loging glm vectors, matrix and quaternios
  Hazel/src/Hazel/Core/Log.h
Labels: Impact:Maintenance
